INSERT INTO estados (id, nome, sigla, regiao, populacao)
VALUES (1000, 'REPÚBLICA FERRAZ', 'RP', 'Sul', 10.4);

SELECT * FROM WM.estados

INSERT INTO estados (nome, sigla, regiao, populacao)
VALUES ('UNIÃO FLASCO', 'UF', 'Norte', 6.9);

--RESUMO DA OPERA, O ID POR SER AUTO INCREMENTO
--VAI ENTRAR COMO 1001 NO SEGUNDO INSERT
--POIS FOI DEFINIDO 1000 NO ANTERIOR
--VALE RESSALTAR QUE DE FORMA MANUAL VOCÊ PODE
--COLOCAR OS IDs ENTRE 38 E 1000